# Generated by Django 3.1.3 on 2020-11-08 23:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201108_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(default='no_image.jpg', upload_to=blog.models.upload_image_to),
        ),
    ]
