# Generated by Django 3.1.3 on 2020-11-08 23:22

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=blog.models.upload_image_to),
        ),
    ]
