# Generated by Django 3.1.3 on 2020-11-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201109_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
